// <auto-generated />
namespace mobSocial.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PerApplicationEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PerApplicationEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201710031100108_PerApplicationEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
